const express = require('express');
const app = express();

const PORT = process.env.PORT || 3000;
const ORIGINAL_API_BASE = 'https://api.storymax.app';

// Local JSON Files Import
const subscriptionData = require('./subscription.json');
const structData = require('./struct.json');

// Full CORS Middleware
app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    if (req.method === 'OPTIONS') {
        return res.sendStatus(200);
    }
    next();
});

app.use(express.json());

function sendJsonWithCdnProxy(res, req, data) {
    res.header("Cache-Control", "public, max-age=3600");
    return res.json(data);
}

// ---------------- EPISODE UNLOCK ENGINE FIX ----------------
function unlockEpisodeData(obj) {
    if (!obj || typeof obj !== 'object') return obj;

    if (Array.isArray(obj)) {
        return obj.map(item => unlockEpisodeData(item));
    }

    for (let key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key)) {
            // Target 'lock', 'isLocked', 'isPay' keys explicitly
            if (key === 'lock' || key === 'isLocked' || key === 'isPay' || key === 'is_locked' || key === 'is_pay' || key === 'locked') {
                obj[key] = false;
            }
            if (key === 'unlockStatus' || key === 'lockStatus') {
                obj[key] = 1;
            }
            if (key === 'isVIP' || key === 'isVip' || key === 'isWtch' || key === 'hasPermission') {
                obj[key] = true;
            }
            
            // Recursive check for nested JSON objects & arrays
            if (typeof obj[key] === 'object') {
                obj[key] = unlockEpisodeData(obj[key]);
            }
        }
    }
    return obj;
}

// ---------------- LOCAL CUSTOM ENDPOINTS ----------------

app.get('/', (req, res) => {
    res.json({ status: 200, message: "EliteMods StoryMax Proxy is Fully Live & Unlocked!" });
});

// 1. Subscription API
app.get('/userservice/v1/profile/subscription', (req, res) => {
    sendJsonWithCdnProxy(res, req, subscriptionData);
});

// 2. Subscription State API
app.get('/userservice/v1/profile/subscription/state', (req, res) => {
    sendJsonWithCdnProxy(res, req, subscriptionData);
});

// 3. Homepage Struct API
app.get('/feedservice/v1/homepage/struct', (req, res) => {
    sendJsonWithCdnProxy(res, req, structData);
});

// ---------------- LIVE PROXY HANDLER ----------------

app.use(async (req, res) => {
    try {
        const targetUrl = `${ORIGINAL_API_BASE}${req.originalUrl}`;

        // Dynamic Session ID Generator
        const clientSessionId = req.headers['ep_session_id'] || req.headers['epsessionid'];
        const autoGeneratedSessionId = `${Math.floor(10000000 + Math.random() * 90000000)}_${Math.floor(Date.now() / 1000)}`;

        const headers = {
            'appVersion': req.headers['appversion'] || req.headers['appVersion'] || '14',
            'platform': req.headers['platform'] || '0',
            'deviceId': req.headers['deviceid'] || req.headers['deviceId'] || 'acac549b0ef02489',
            'os': req.headers['os'] || 'Android 16 (API 36)',
            'network_type': req.headers['network_type'] || req.headers['network-type'] || 'WIFI',
            'ep_session_id': clientSessionId || autoGeneratedSessionId,
            'X-AYUSH-KEY': req.headers['x-ayush-key'] || req.headers['X-AYUSH-KEY'] || 'LEGEND_2026_SECRET',
            'Authorization': req.headers['authorization'] || req.headers['Authorization'] || '',
            'User-Agent': req.headers['user-agent'] || 'ktor-client',
            'Content-Type': 'application/json',
            'ts': req.headers['ts'] || Math.floor(Date.now() / 1000).toString()
        };

        const fetchOptions = {
            method: req.method,
            headers: headers
        };

        if (req.method !== 'GET' && req.method !== 'HEAD' && req.body && Object.keys(req.body).length > 0) {
            fetchOptions.body = JSON.stringify(req.body);
        }

        const response = await fetch(targetUrl, fetchOptions);
        
        const contentType = response.headers.get("content-type");
        if (contentType && contentType.includes("application/json")) {
            let data = await response.json();
            
            // AUTOMATIC OVERWRITE "lock": true -> "lock": false
            data = unlockEpisodeData(data);

            res.status(response.status).json(data);
        } else {
            const textData = await response.text();
            res.status(response.status).send(textData);
        }

    } catch (error) {
        res.status(500).json({
            status: "PROXY_ERROR",
            message: error.message
        });
    }
});

app.listen(PORT, () => {
    console.log(`Server running live on port ${PORT}`);
});
